import = [
  "~/.config/alacritty/rose-pine.toml"
]

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[font.normal]
family = "JetBrainsMono Nerd Font"

[env]
term = "xterm-256color"
