import = [
  "~/.config/alacritty/rose-pine.toml"
]

[window]
dynamic_title = true
padding = { x = 5, y = 5 }

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[env]
term = "xterm-256color"
