#!/usr/bin/env bash

languages=$(echo "javascript typescript c cpp python" | tr " " "\n")
core_utils=$(echo "find xargs sed awk" | tr " " "\n")
selected=$(echo -e "$languages\n$core_utils" | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

read -p "QUERY PLEASE: " query

if echo "$languages" | grep -qs $selected; then
    tmux split-window -p 40 -h bash -c "curl -s cht.sh/$selected/$(echo "$query" | tr " "  "+") | less -R"
else
    tmux split-window -p 40 -h bash -c "curl -s cht.sh/$selected~$query | less -R"
fi
