#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    session=$1
else
    session=$(find ~ ~/workspace/ ~/.dotfiles/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $session ]]; then
    exit 0
fi


session_name=$(basename "$session" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name -c $session
    exit 0
fi

if ! tmux has-session -t="$session_name" 2> /dev/null; then
    tmux new-session -ds "$session_name" -c "$session" 
fi

tmux switch-client -t "$session_name"
