#!/usr/bin/env bash

# Use fzf to search for a file starting from the root directory
selected_file=$(find /usr -type f 2>/dev/null | fzf)

# Check if a file was selected
if [ -n "$selected_file" ]; then
    # Create a new tmux window and open the selected file with nvim
    tmux new-window "nvim '$selected_file'"
else
    echo "No file selected."
fi
